baseURL: "https://javed.tech/"
title: Javed Hussain
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Blog
      url: posts/
      weight: 2
    - name: Search
      url: search/
      weight: 3
    # - name: Tags
    #   url: tags/
    #   weight: 4
    # - name: Categories
    #   url: categories/
    #   weight: 5

params:
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  assets:
    favicon: images/avatar.svg
  label:
    text: JH
  profileMode:
    enabled: true
    title: "Javed Hussain" # optional default will be site title
    subtitle: "Software Craftsperson"
    imageUrl: images/avatar.svg
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    buttons:
        - name: Resume
          url: https://raw.githubusercontent.com/javedh-dev/javedh-dev.github.io/master/data/Javed_SE_Resume.pdf

  homeInfoParams:
    enabled: false
    Title: "Welcome visitor ğŸ‘‹"
    Content: >
      -  I ğŸ’– to write about my thoughts ğŸ’­ and experiences ğŸ‘¨â€ğŸ’» here. Hope you would enjoy ğŸ˜Š!!!

  socialIcons:
    - name: "Github"
      url: "https://github.com/javedh-dev"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/javedh-dev"
    - name: "Twitter"
      url: "https://twitter.com/javedh_dev"
    - name: "Instagram"
      url: "https://www.instagram.com/javedh.dev/"
    - name: "Email"
      url: "mailto:javedh.dev@gmail.com"
    - name: "Youtube"
      url: "https://www.youtube.com/channel/UC9ZHPvoBkR5RjrZQqSFtCrQ"