baseURL: "https://javed.tech/"
title: Javed Hussain
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Archives
      url: archives
      weight: 2
    - name: Search
      url: search/
      weight: 3
    - name: Tags
      url: tags/
      weight: 4
    - name: Categories
      url: categories/
      weight: 5

params:
  profileMode:
    enabled: false

  homeInfoParams:
    enabled: true
    Title: "Welcome visitor ğŸ‘‹"
    Content: >
      -  I ğŸ’– to write about my thoughts ğŸ’­ and experiences ğŸ‘¨â€ğŸ’» here. Hope you would enjoy ğŸ˜Š!!!

  socialIcons:
    - name: "Github"
      url: "https://github.com/javedh-dev"
    - name: "Email"
      url: "mailto:javedh.dev@gmail.com"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/javedh-dev"
